<?php
	return array(
		'okay, cupid' => 'http://blogs.kqed.org/filmschoolshorts/2013/03/13/episode-101-okay-cupid/',
		'growing pains' => 'http://blogs.kqed.org/filmschoolshorts/2013/03/12/episode-102-growing-pains/',
		'letting go' => 'http://blogs.kqed.org/filmschoolshorts/2013/03/11/episode-103-letting-go/',
		'fire and fury' => 'http://blogs.kqed.org/filmschoolshorts/2013/03/10/fire-and-fury/',
		'blood is thicker than mud' => 'http://blogs.kqed.org/filmschoolshorts/2013/03/09/blood-is-thicker-than-mud/',
		'man up' => 'http://blogs.kqed.org/filmschoolshorts/2013/03/08/man-up/',
		'sum of its parts' => 'http://blogs.kqed.org/filmschoolshorts/2013/03/07/sum-of-its-parts/',
		'risky business' => 'http://blogs.kqed.org/filmschoolshorts/2013/03/06/risky-business/',
		'creature comforts' => 'http://blogs.kqed.org/filmschoolshorts/2013/03/05/creature-comforts/',
		'strange bedfellows' => 'http://blogs.kqed.org/filmschoolshorts/2013/03/04/strange-bedfellows/'
	);

?>